name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: vlang/v
        path: vlang
    - name: Build VLang
      run: make -C vlang
    - name: Copy V compiler into path
      run: cp vlang/v .
    - name: Run unit tests
      run: make test
