name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: https://github.com/vlang/v
    - name: Test gcc
      run: cd v ; make ; cp v /usr/bin
    - name: Run unit tests
      run: make test
